language: en-US
tone_instructions: 'Focus on logic correctness, security issues, and browser extension best practices. Be concise but thorough.'

reviews:
  profile: assertive

  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - main
      - develop
      - deepsource-transform-*
      - copilot-*

  high_level_summary: true
  high_level_summary_in_walkthrough: true
  review_status: false

  path_instructions:
    - path: 'background.js'
      instructions: |
        This is a browser extension background script. Pay attention to:
        - Message passing security (validate sender origins)
        - Async error handling in storage operations
        - Container isolation logic (cookieStoreId checks)
        - Storage quota management (100KB limit for sync)

    - path: 'state-manager.js'
      instructions: |
        State management module. Check for:
        - Race conditions in async operations
        - Proper container isolation
        - Memory leaks (WeakMap usage)
        - Error propagation

    - path: '**/*.test.js'
      instructions: |
        Test files. Verify:
        - Edge cases are covered
        - Error scenarios are tested
        - Mocks are properly set up
        - Coverage is comprehensive

    - path: 'manifest.json'
      instructions: |
        Extension manifest. Ensure:
        - Manifest V2 compliance (required for webRequestBlocking)
        - Minimal required permissions
        - CSP is properly configured
        - Browser-specific settings are correct

  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  code_guidelines:
    enabled: true
    filePatterns:
      - '**/.github/copilot-instructions.md'
      - '**/README.md'
      - '**/docs/**/*.md'
